# Generated by Django 4.0.4 on 2022-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
