# Generated by Django 4.0.5 on 2022-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
